# Generated by Django 5.2.11 on 2026-02-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
